DROP TABLE IF EXISTS EMPLOYEES;
  
CREATE TABLE EMPLOYEES (
  empId INT PRIMARY KEY,
  emp_Name VARCHAR(250) NOT NULL,
  title VARCHAR(250) NOT NULL,
bunit VARCHAR(250) NOT NULL,
place VARCHAR(250) NOT NULL,
sId VARCHAR(250) NOT NULL,
competencies VARCHAR(250) NOT NULL,
salary int NOT NULL,
);